In [2]:
import pandas as pd
import tensorlayer as tl
import matplotlib.pyplot as plt

import json

In [29]:
file_list = sorted(tl.files.load_file_list(path="./", regx='.*png.json', printable=False))
file_list

['0833.png.json', '0852.png.json', '0883.png.json', '0900.png.json']

In [30]:
dfs = [pd.read_json(i) for i in file_list]
dfs[0]

,model,psnr_lr,ssim_lr,psnr_hr_4,ssim_hr_4,psnr_hr,ssim_hr,psnr_bic_hr,ssim_bic_hr
0,g-10.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
1,g-20.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
2,g-30.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
3,g-40.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
4,g-50.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
...,...,...,...,...,...,...,...,...,...
78,g-790.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
79,g-800.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
80,g-810.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
81,g-820.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295
82,g-830.h5,36.871339,0.963865,2.705141,-0.000018,2.700781,0.000056,18.480638,0.580295

In [31]:
dfs[1].head().add(dfs[0])

,model,psnr_lr,ssim_lr,psnr_hr_4,ssim_hr_4,psnr_hr,ssim_hr,psnr_bic_hr,ssim_bic_hr
0,g-10.h5g-10.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
1,g-20.h5g-20.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
2,g-30.h5g-30.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
3,g-40.h5g-40.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
4,g-50.h5g-50.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
...,...,...,...,...,...,...,...,...,...
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
avg_df = dfs[0].drop(["model"], axis=1)

for i in range(1,len(dfs)):
    avg_df = avg_df.add(dfs[i].drop(["model"], axis=1), fill_value=0, axis=0)
    
# avg_df /= 3

avg_df.head()

,psnr_lr,ssim_lr,psnr_hr_4,ssim_hr_4,psnr_hr,ssim_hr,psnr_bic_hr,ssim_bic_hr
0,143.825095,3.858799,37.634125,-0.003155,37.270222,0.300317,74.244476,1.82291
1,143.825095,3.858799,37.634125,-0.003155,37.270222,0.300317,74.244476,1.82291
2,143.825095,3.858799,37.634125,-0.003155,37.270222,0.300317,74.244476,1.82291
3,143.825095,3.858799,37.634125,-0.003155,37.270222,0.300317,74.244476,1.82291
4,143.825095,3.858799,37.634125,-0.003155,37.270222,0.300317,74.244476,1.82291