In [34]:
import pandas as pd
import tensorlayer as tl
import matplotlib.pyplot as plt

import json

In [35]:
file_list = sorted(tl.files.load_file_list(path="./", regx='.*png.json', printable=False))
file_list

[]

In [36]:
dfs = [pd.read_json(i) for i in file_list]
dfs[0]

IndexError: list index out of range

In [31]:
dfs[1].head().add(dfs[0])

,model,psnr_lr,ssim_lr,psnr_hr_4,ssim_hr_4,psnr_hr,ssim_hr,psnr_bic_hr,ssim_bic_hr
0,g-10.h5g-10.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
1,g-20.h5g-20.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
2,g-30.h5g-30.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
3,g-40.h5g-40.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
4,g-50.h5g-50.h5,72.251444,1.93175,22.472224,-0.002071,22.201218,0.241297,41.678533,1.121935
...,...,...,...,...,...,...,...,...,...
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN